title: the mind of rathewolf
description: thoughts, philosophies, writings, expressions

remote_theme: ronv/sidey

# theme specific stuff
site: the mind of rathewolf
#url: #yoururl

#defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/pages/"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "/posts/"
      type: "posts"
    values:
      layout: "post"
